services:
  spark-master:
    image: ghcr.io/auduvignac/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - ROLE=MASTER
    ports:
      - "8080:8080"  # Spark UI (master)
      - "7077:7077"  # Spark master service port
    volumes:
      - ./src/main/resources/log4j2-master.properties:/opt/spark/conf/log4j2.properties
    restart: unless-stopped

  spark-worker:
    image: ghcr.io/auduvignac/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=WORKER
    volumes:
      - ./:/app
      - ./src/main/resources/log4j2-worker.properties:/opt/spark/conf/log4j2.properties
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-submit:
    image: ghcr.io/auduvignac/spark:latest
    container_name: spark-submit
    command: ["tail", "-f", "/dev/null"]
    environment:
      - SPARK_MODE=submit
      - SPARK_MASTER_URL=spark://spark-master:7077
      - ROLE=SUBMIT
    volumes:
      - ./:/app
      - ./src/main/resources/log4j2-submit.properties:/opt/spark/conf/log4j2.properties
    working_dir: /app
    depends_on:
      - spark-master
    restart: unless-stopped