name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
      # CR_PAT
      # CR : Container Registry (le service GHCR de GitHub)
      # PAT Personal Access Token (type de jeton généré)
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u auduvignac --password-stdin

      - name: Build and Push
        run: |
          IMAGE_NAME=ghcr.io/auduvignac/spark:latest
          docker build -f Dockerfile.custom -t $IMAGE_NAME .
          docker push $IMAGE_NAME